### ISSUE TITLE
Start.bat / Windows deploy of v2 fails with missing output file

### ISSUE THREAD

**Issue by vandalix2** [tanzu-factory/tap-jumpstart#17]
kicked off the start.bat file on a Windows based Docker Desktop running K8s.

Uploaded and configured all the requested info as per v1 deployment however this time when it comes time to click the install button i get the following error : 

=================================================
============= Starting Merlin... ================
=================================================
Saving jumpstart files (tap-values, output, env) in binaries directory.../workspace/merlin/run-merlin.sh: line 8: syntax error near unexpected token `&&'
/workspace/merlin/run-merlin.sh: line 8: `      && (test -f $HOME/configs/output && cp $HOME/configs/output /workspace/binaries/) || true'
child process exited with code 2
Saving jumpstart files (tap-values, output, env) in binaries directory...cp: cannot stat '/root/configs/output': No such file or directory
COMPLETE.
child process exited with code 0
Error: Command failed: cat $HOME/configs/output
cat: /root/configs/output: No such file or directory

From what i can see within the container, the "output" file is completely missing from any of the relevant directories.  Not sure when it gets generated and whats stored in this file, but it seems to be important :)

**Comment by alinahid477** [comment]
Fixed in release 2.21092023
