### ISSUE TITLE
TokenRequest warning on K8s 1.27

### ISSUE THREAD

**Issue by davidk355** [tanzu-factory/tap-jumpstart#18]
When connecting to K8s 1.27 the following warning is displayed at the binaries screen which halts the connection.

Error: Command failed: test -f $HOME/tokenfile && export $(cat $HOME/tokenfile | xargs) || echo tokenfilenotfound > /dev/null 2>&1 && kubectl get pod -n cartographer-system | grep cartographer-controller
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
No resources found in cartographer-system namespace.
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.

**Comment by alinahid477** [comment]
fixed in release 2.21092023
